import turtle
Rafael = turtle.Turtle()
Rafael.color("black")
Rafael.forward(90)
Rafael.left(90)
Rafael.forward(90)
Rafael.left(90)
Rafael.forward(90)
Rafael.left(90)
Rafael.forward(90)

Rafael.color("white")
Rafael.forward(90)
Rafael.right(90)
Rafael.forward(90)
Rafael.right(90)
Rafael.forward(90)
Rafael.forward(90)
Rafael.right(90)
Rafael.forward(90)
Rafael.right(90)

Rafael.color("red")
Rafael.left(-45)
Rafael.forward(-65)
Rafael.left(-90)
Rafael.forward(-65)
Rafael.right(90)

Rafael.color("red")
Rafael.forward(50)
Rafael.right(90)
Rafael.forward(50)
Rafael.right(45)

Rafael.color("black")
Rafael.forward(90)
Rafael.right(90)
Rafael.forward(80)
Rafael.right(90)
Rafael.forward(90)
Rafael.right(90)
Rafael.forward(80)

Rafael.right(90)
Rafael.forward(90)
Rafael.right(90)
Rafael.forward(30)
Rafael.right(90)
Rafael.forward(50)
Rafael.right(90)
Rafael.forward(30)
Rafael.right(90)
Rafael.forward(50)
Rafael.right(90)
Rafael.forward(90)
Rafael.forward(45)
Rafael.right(90)
Rafael.forward(50)
Rafael.right(90)
Rafael.forward(30)
Rafael.right(90)
Rafael.forward(50)
Rafael.right(90)
Rafael.forward(30)